apiVersion: v1
kind: Service
metadata:
  name: gateway-llm
  namespace: ai-gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: llm
    app.kubernetes.io/part-of: ai-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: llm
  ports:
    - name: http-llm
      port: 8082
      targetPort: http-llm
