// AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
// Source of truth: tokens.json. Run `npm run gen:tokens` after editing it.

export const colors = {
  indigo: {
    "1": "#fdfdfe",
    "2": "#f7f9ff",
    "3": "#edf2fe",
    "4": "#dfe9ff",
    "5": "#cedcff",
    "6": "#b8ccff",
    "7": "#9eb6ff",
    "8": "#7c97f7",
    "9": "#3d63dd",
    "10": "#3358d4",
    "11": "#324fbe",
    "12": "#1f2d5c",
    d1: "#11131f",
    d2: "#141726",
    d3: "#1c2348",
    d4: "#202d5f",
    d5: "#243573",
    d6: "#283f87",
    d7: "#324da3",
    d8: "#3a5fc7",
    d9: "#3d63dd",
    d10: "#5070e6",
    d11: "#9eb1ff",
    d12: "#d6e1ff",
  },
  slate: {
    "1": "#fcfcfd",
    "2": "#f9f9fb",
    "3": "#f0f0f3",
    "4": "#e8e8ec",
    "5": "#e0e1e6",
    "6": "#d9d9e0",
    "7": "#cdced6",
    "8": "#b9bbc6",
    "9": "#8b8d98",
    "10": "#80828d",
    "11": "#62636c",
    "12": "#1e1f24",
    d1: "#111113",
    d2: "#18191b",
    d3: "#212225",
    d4: "#272a2d",
    d5: "#2e3135",
    d6: "#363a3f",
    d7: "#43484e",
    d8: "#5a6169",
    d9: "#696e77",
    d10: "#777b84",
    d11: "#b0b4ba",
    d12: "#edeef0",
  },
  sev: {
    critical: "#9610fa",
    criticalBg: "#f7e6ff",
    criticalFg: "#6b1faf",
    high: "#e7000b",
    highBg: "#ffe2e2",
    highFg: "#c10007",
    medium: "#ff6900",
    mediumBg: "#ffedd4",
    mediumFg: "#ca3500",
    low: "#efb100",
    lowBg: "#fef9c2",
    lowFg: "#894b00",
    info: "#2b7fff",
    infoBg: "#dbeafe",
    infoFg: "#1447e6",
  },
  status: {
    open: "#2b7fff",
    openBg: "#dbeafe",
    resolved: "#00a63e",
    resolvedBg: "#dcfce7",
    suppressed: "#62636c",
    suppressedBg: "#f0f0f3",
    escalated: "#f6339a",
    escalatedBg: "#fce7f3",
    deferred: "#00a6f4",
    deferredBg: "#cefafe",
  },
  brand: {
    cyanFrom: "#06D4F9",
    cyanTo: "#17A6DE",
    actionFrom: "#615FFF",
    actionTo: "#9810FA",
    deep: "#0F4062",
    bright: "#4CC0FF",
    tusk: "#FFC120",
  },
} as const

export const fonts = {
  ui: "\"Inter\", -apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Segoe UI\", Roboto, sans-serif",
  mono: "\"JetBrains Mono\", \"SF Mono\", \"IBM Plex Mono\", ui-monospace, Menlo, monospace",
  display: "\"Inter\", \"SF Pro Display\", -apple-system, sans-serif",
} as const

export const radii = {
  "1": "2px",
  "2": "4px",
  "3": "6px",
  "4": "8px",
  "5": "12px",
  "6": "16px",
  pill: "999px",
} as const

/** Light-theme shadow values. For dark-mode-aware shadows in CSS, prefer the
 * `shadow-1`.. `shadow-4` Tailwind utilities (bound to tokens.css), which
 * automatically switch under `.dark`. */
export const shadows = {
  "1": "0 1px 2px rgba(15,23,42,.04), 0 1px 1px rgba(15,23,42,.04)",
  "2": "0 1px 3px rgba(15,23,42,.06), 0 4px 8px rgba(15,23,42,.04)",
  "3": "0 4px 8px rgba(15,23,42,.06), 0 12px 32px rgba(15,23,42,.08)",
  "4": "0 12px 32px rgba(15,23,42,.10), 0 24px 64px rgba(15,23,42,.10)",
  focus: "0 0 0 3px rgba(61,99,221,.25)",
} as const

export type Colors = typeof colors
