#!/usr/bin/env node
// Generates src/styles/tokens.css and src/styles/tokens.ts from tokens.json.
//
// tokens.json is the single source of truth for the design system's raw
// tokens (colors, spacing, radii, shadows, fonts). Edit tokens.json, then
// run `npm run gen:tokens` to regenerate both output files. Do not hand-edit
// the generated files — they are overwritten on every run.

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

/** @type {any} */
const tokens = JSON.parse(readFileSync(path.join(root, 'tokens.json'), 'utf8'))

const GENERATED_NOTICE_CSS = `/* AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
 * Source of truth: tokens.json. Run \`npm run gen:tokens\` after editing it. */`

const GENERATED_NOTICE_TS = `// AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
// Source of truth: tokens.json. Run \`npm run gen:tokens\` after editing it.`

/** Converts a tokens.json key into the CSS custom-property suffix the
 * designer's token list uses: "d1" -> "d-1", "criticalBg" -> "critical-bg". */
function kebab(key) {
  if (/^d\d+$/.test(key)) return key.replace(/^d(\d+)$/, 'd-$1')
  return key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

function flatCssVars(prefix, obj) {
  return Object.entries(obj).map(
    ([key, value]) => `  --${prefix}-${kebab(key)}: ${value};`,
  )
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

const root_ = []
const dark = []

root_.push('  /* Indigo scale (light) + Indigo dark-surface scale */')
root_.push(...flatCssVars('indigo', tokens.indigo))
root_.push('')
root_.push('  /* Slate scale (light) + Slate dark-surface scale */')
root_.push(...flatCssVars('slate', tokens.slate))
root_.push('')
root_.push('  /* Severity */')
root_.push(...flatCssVars('sev', tokens.sev))
root_.push('')
root_.push('  /* Status */')
root_.push(...flatCssVars('status', tokens.status))
root_.push('')
root_.push('  /* Brand gradients */')
root_.push(...flatCssVars('brand', tokens.brand))
root_.push('')
root_.push(
  '  /* Surface: follows the shadcn theme in src/index.css, which also owns --border */',
)
for (const [key, value] of Object.entries(tokens.surface)) {
  const name = `--${kebab(key)}`
  root_.push(`  ${name}: ${value.light};`)
  if (value.dark !== value.light) dark.push(`  ${name}: ${value.dark};`)
}
root_.push('')
root_.push('  /* Spacing */')
for (const [key, value] of Object.entries(tokens.space)) {
  root_.push(`  --space-${key}: ${value};`)
}
root_.push('')
root_.push('  /* Radius */')
for (const [key, value] of Object.entries(tokens.radius)) {
  root_.push(`  --r-${key}: ${value};`)
}
root_.push('')
root_.push('  /* Shadow (light values; dark overrides below under .dark) */')
for (const [key, value] of Object.entries(tokens.shadow)) {
  root_.push(`  --shadow-${key}: ${value.light};`)
  if (value.dark !== value.light) dark.push(`  --shadow-${key}: ${value.dark};`)
}
root_.push('')
root_.push('  /* Typography */')
for (const [key, value] of Object.entries(tokens.font)) {
  root_.push(`  --font-${key}: ${value};`)
}

const css = `${GENERATED_NOTICE_CSS}

:root {
${root_.join('\n')}
}

.dark {
${dark.join('\n')}
}
`

writeFileSync(path.join(root, 'src/styles/tokens.css'), css)

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function tsObjectLiteral(obj, indent) {
  const inner = indent + '  '
  const entries = Object.entries(obj).map(([key, value]) => {
    const safeKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : JSON.stringify(key)
    return `${inner}${safeKey}: ${JSON.stringify(value)},`
  })
  return `{\n${entries.join('\n')}\n${indent}}`
}

const lightShadows = Object.fromEntries(
  Object.entries(tokens.shadow).map(([key, value]) => [key, value.light]),
)

const ts = `${GENERATED_NOTICE_TS}

export const colors = {
  indigo: ${tsObjectLiteral(tokens.indigo, '  ')},
  slate: ${tsObjectLiteral(tokens.slate, '  ')},
  sev: ${tsObjectLiteral(tokens.sev, '  ')},
  status: ${tsObjectLiteral(tokens.status, '  ')},
  brand: ${tsObjectLiteral(tokens.brand, '  ')},
} as const

export const fonts = ${tsObjectLiteral(tokens.font, '')} as const

export const radii = ${tsObjectLiteral(tokens.radius, '')} as const

/** Light-theme shadow values. For dark-mode-aware shadows in CSS, prefer the
 * \`shadow-1\`.. \`shadow-4\` Tailwind utilities (bound to tokens.css), which
 * automatically switch under \`.dark\`. */
export const shadows = ${tsObjectLiteral(lightShadows, '')} as const

export type Colors = typeof colors
`

writeFileSync(path.join(root, 'src/styles/tokens.ts'), ts)

console.log('Generated src/styles/tokens.css and src/styles/tokens.ts from tokens.json')
