/** Every user-visible string the data table renders, in one place. */
export const LABELS = {
  items: 'items',
  rowsPerPage: 'Rows per page',
  of: 'of',
  page: (n: number) => `Page ${n}`,
  goToRange: 'Go to range…',
  noRange: 'No matching range',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  columns: 'Columns',
  toggleColumns: 'Toggle columns',
  export: 'Export',
  actions: 'Actions',
  actionsFor: (label: string) => `Actions for ${label}`,
  selected: 'selected',
  clearSelection: 'Clear selection',
  selectAll: 'Select all rows',
  selectRow: 'Select row',
  toggleDetails: 'Toggle row details',
  reorderColumn: 'Reorder column',
  table: 'Table',
  noResults: 'No results',
  error: 'Something went wrong loading this data.',
} as const
