// Explicit order (the same order as docs/README.md) instead of autogenerated
// alphabetical, and no front matter in the docs so GitHub keeps rendering
// them cleanly. Doc ids are the file names under ../docs.
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    { type: 'doc', id: 'README', label: 'Overview' },
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['getting-started', 'architecture', 'configuration', 'security-model', 'authentication'],
    },
    {
      type: 'category',
      label: 'Operating the gateway',
      collapsed: false,
      items: ['connectors-and-credentials', 'profiles', 'models', 'skills', 'llm-plane', 'detection-agent', 'observability', 'api'],
    },
    { type: 'doc', id: 'third-party-notices', label: 'Third-Party Notices' },
  ],
};

export default sidebars;
