package handlers

import (
	"encoding/json"
	"errors"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"

	"github.com/Tuskira/tusk-ai-secured-gateway/pkg/analytics"
)

// monitoringFixture is shared with the console's tests, like
// consoleFixture: TestTokenMonitoring_ConsoleContract replays each request
// through the real handlers and compares the answers with the file;
// web/src/test/token-monitoring*.test.ts(x) render them. Regenerate after an
// intended API change with
//
//	UPDATE_CONSOLE_FIXTURES=1 go test ./internal/api/handlers -run TestTokenMonitoring_ConsoleContract
const monitoringFixture = "../../../web/src/test/fixtures/token-monitoring-api.json"

type monitoringContract struct {
	Comment string `json:"_comment"`
	// Overview7d is GET /analytics/token-monitoring?window=7d.
	Overview7d contractExchange `json:"overview_7d"`
	// OverviewToday is the same page after switching to Today.
	OverviewToday contractExchange `json:"overview_today"`
	// Model is GET /analytics/token-monitoring/model?model=claude-sonnet-4-5&window=7d.
	Model contractExchange `json:"model"`
	// Key is GET /analytics/token-monitoring/keys/{id}?window=7d.
	Key contractExchange `json:"key"`
}

func TestTokenMonitoring_ConsoleContract(t *testing.T) {
	update := os.Getenv("UPDATE_CONSOLE_FIXTURES") != ""
	var fx monitoringContract
	raw, err := os.ReadFile(filepath.FromSlash(monitoringFixture))
	switch {
	case err == nil:
		if err := json.Unmarshal(raw, &fx); err != nil {
			t.Fatalf("decode fixture: %v", err)
		}
	case !update || !errors.Is(err, fs.ErrNotExist):
		t.Fatalf("read fixture: %v", err)
	}
	fx.Comment = "Generated by internal/api/handlers/analytics_monitoring_contract_test.go (UPDATE_CONSOLE_FIXTURES=1). Do not edit by hand."

	r := &fakeMonReader{fakeAnalyticsReader: &fakeAnalyticsReader{}}
	d, ids := monDeps(t, r)
	h := Analytics{Deps: d}
	check := func(name string, ex *contractExchange, w *httptest.ResponseRecorder) {
		t.Helper()
		var got any
		if err := json.Unmarshal(w.Body.Bytes(), &got); err != nil {
			t.Fatalf("%s: response is not JSON: %s", name, w.Body.String())
		}
		if update {
			b, _ := json.Marshal(got)
			ex.Status, ex.Response = w.Code, b
			return
		}
		var want any
		if err := json.Unmarshal(ex.Response, &want); err != nil {
			t.Fatalf("%s: fixture response is not JSON: %v", name, err)
		}
		if w.Code != ex.Status || !reflect.DeepEqual(got, want) {
			gotJSON, _ := json.MarshalIndent(got, "", "  ")
			t.Errorf("%s: the handler answers %d\n%s\nbut the console fixture has %d\n%s", name, w.Code, gotJSON, ex.Status, ex.Response)
		}
	}
	get := func(pattern, url string, fn http.HandlerFunc) *httptest.ResponseRecorder {
		return serve(http.MethodGet, pattern, fn, withPrincipal(httptest.NewRequest(http.MethodGet, url, nil), "tenant-a", "viewer"))
	}

	end := time.Date(2026, 1, 8, 12, 0, 0, 0, time.UTC)
	start := end.Add(-7 * 24 * time.Hour)
	f := func(v float64) *float64 { return &v }
	days := func(tokens ...uint64) []analytics.TokenBucket {
		out := make([]analytics.TokenBucket, len(tokens))
		for i, n := range tokens {
			out[i] = analytics.TokenBucket{Bucket: start.Truncate(24 * time.Hour).Add(time.Duration(i) * 24 * time.Hour), Tokens: n}
		}
		return out
	}
	sonnet := analytics.TokenUsage{Tokens: 315000, PromptTokens: 210000, CompletionTokens: 105000, CacheReadTokens: 2400000, CacheWriteTokens: 180000, CostUSD: f(4.1234), Calls: 42, PrevTokens: 200000}
	gpt := analytics.TokenUsage{Tokens: 24000, PromptTokens: 20000, CompletionTokens: 4000, CacheReadTokens: 30000, Calls: 6, UnpricedCalls: 6}
	tiny := analytics.TokenUsage{Tokens: 12, PromptTokens: 10, CompletionTokens: 2, CostUSD: f(0.0000097), Calls: 1}
	r.mon = &analytics.TokenMonitoring{
		Window: analytics.Window7d, Start: start, End: end, Granularity: analytics.GranularityDay,
		Totals: analytics.TokenUsage{Tokens: 339012, PromptTokens: 230010, CompletionTokens: 109002, CacheReadTokens: 2430000,
			CacheWriteTokens: 180000, CostUSD: f(4.1234097), Calls: 49, UnpricedCalls: 6, PrevTokens: 200000},
		ByModel: []analytics.ModelTokenUsage{
			{Model: "claude-sonnet-4-5", TokenUsage: sonnet},
			{Model: "gpt-5", TokenUsage: gpt},
			{Model: "local-coder", TokenUsage: tiny},
		},
		ByKey: []analytics.KeyTokenUsage{
			{KeyID: ids["ci-bot"], Source: "gateway", Models: 2, TokenUsage: analytics.TokenUsage{Tokens: 300000, PromptTokens: 200000, CompletionTokens: 100000, CostUSD: f(3.9), Calls: 40, PrevTokens: 200000}},
			{KeyID: ids["collector"], Source: "interceptor", Models: 1, TokenUsage: analytics.TokenUsage{Tokens: 24000, PromptTokens: 20000, CompletionTokens: 4000, Calls: 6, UnpricedCalls: 6}},
			{KeyID: ids["ops"], Source: "gateway", Models: 1, TokenUsage: analytics.TokenUsage{Tokens: 15000, PromptTokens: 10000, CompletionTokens: 5000, CostUSD: f(0.2234), Calls: 2}},
			{KeyID: "deleted-key", Source: "gateway", Models: 1, TokenUsage: tiny},
		},
		Burn: days(40000, 0, 81000, 55000, 60012, 45000, 30000, 28000),
	}
	check("overview_7d", &fx.Overview7d, get("/analytics/token-monitoring", "/analytics/token-monitoring?window=7d", h.TokenMonitoring))

	todayStart := end.Truncate(24 * time.Hour)
	r.mon = &analytics.TokenMonitoring{
		Window: analytics.WindowToday, Start: todayStart, End: end, Granularity: analytics.GranularityHour,
		Totals: analytics.TokenUsage{Tokens: 1500, PromptTokens: 1000, CompletionTokens: 500, CostUSD: f(0.0105), Calls: 3},
		ByModel: []analytics.ModelTokenUsage{
			{Model: "claude-sonnet-4-5", TokenUsage: analytics.TokenUsage{Tokens: 1500, PromptTokens: 1000, CompletionTokens: 500, CostUSD: f(0.0105), Calls: 3}},
		},
		ByKey: []analytics.KeyTokenUsage{
			{KeyID: ids["ops"], Source: "gateway", Models: 1, TokenUsage: analytics.TokenUsage{Tokens: 1500, PromptTokens: 1000, CompletionTokens: 500, CostUSD: f(0.0105), Calls: 3}},
		},
		Burn: []analytics.TokenBucket{
			{Bucket: todayStart, Tokens: 0}, {Bucket: todayStart.Add(time.Hour), Tokens: 1500},
		},
	}
	check("overview_today", &fx.OverviewToday, get("/analytics/token-monitoring", "/analytics/token-monitoring?window=today", h.TokenMonitoring))

	seen := end.Add(-time.Hour)
	r.mon = &analytics.TokenMonitoring{
		Window: analytics.Window7d, Start: start, End: end, Granularity: analytics.GranularityDay, Totals: sonnet,
		ByModel: []analytics.ModelTokenUsage{},
		ByKey: []analytics.KeyTokenUsage{
			{KeyID: ids["ci-bot"], Source: "gateway", Models: 1, TokenUsage: analytics.TokenUsage{Tokens: 300000, CostUSD: f(3.9), Calls: 40, PrevTokens: 200000}},
			{KeyID: ids["ops"], Source: "gateway", Models: 1, TokenUsage: analytics.TokenUsage{Tokens: 15000, CostUSD: f(0.2234), Calls: 2}},
		},
		Burn: days(40000, 0, 81000, 55000, 60000, 30000, 30000, 19000),
		Sessions: []analytics.SessionTokenUsage{
			{SessionID: "sess-1", KeyID: ids["ci-bot"], Models: []string{"claude-sonnet-4-5"}, LastSeen: seen,
				TokenUsage: analytics.TokenUsage{Tokens: 300000, PromptTokens: 200000, CompletionTokens: 100000, CacheReadTokens: 2400000, CacheWriteTokens: 180000, CostUSD: f(3.9), Calls: 40}},
			{SessionID: "", KeyID: ids["ops"], Models: []string{"claude-sonnet-4-5"}, LastSeen: seen,
				TokenUsage: analytics.TokenUsage{Tokens: 15000, PromptTokens: 10000, CompletionTokens: 5000, CostUSD: f(0.2234), Calls: 2}},
		},
		SessionsTotal: 2,
	}
	check("model", &fx.Model, get("/analytics/token-monitoring/model", "/analytics/token-monitoring/model?model=claude-sonnet-4-5&window=7d", h.TokenMonitoringModel))

	r.mon = &analytics.TokenMonitoring{
		Window: analytics.Window7d, Start: start, End: end, Granularity: analytics.GranularityDay,
		Totals:  analytics.TokenUsage{Tokens: 24000, PromptTokens: 20000, CompletionTokens: 4000, CacheReadTokens: 30000, Calls: 6, UnpricedCalls: 6},
		ByModel: []analytics.ModelTokenUsage{{Model: "gpt-5", TokenUsage: gpt}},
		ByKey:   []analytics.KeyTokenUsage{},
		Burn:    days(0, 0, 24000, 0, 0, 0, 0, 0),
		Sessions: []analytics.SessionTokenUsage{
			{SessionID: "chat-77", KeyID: ids["collector"], Models: []string{"gpt-5"}, LastSeen: seen, TokenUsage: gpt},
		},
		SessionsTotal: 1,
	}
	check("key", &fx.Key, get("/analytics/token-monitoring/keys/{id}", "/analytics/token-monitoring/keys/"+ids["collector"]+"?window=7d", h.TokenMonitoringKey))

	if update {
		out, err := json.MarshalIndent(fx, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.FromSlash(monitoringFixture), append(out, '\n'), 0o644); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
		t.Logf("rewrote %s", monitoringFixture)
	}
}
