/// <reference types="vitest/config" />
import path from 'node:path'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { defineConfig, type Plugin } from 'vite'
import { closeSync, openSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createRequire } from 'node:module'

// rollup-plugin-license is `module.exports = fn` (CommonJS "export =", no
// __esModule flag) with a .d.ts written in `export default` syntax for
// bundler-mode consumers; under this project's `moduleResolution:
// "nodenext"` (tsconfig.node.json), a plain `import license from
// 'rollup-plugin-license'` type-checks as the whole module namespace
// instead of the callable default, so require() it directly instead --
// this is exactly what the real CJS interop does at runtime anyway.
const license: typeof import('rollup-plugin-license').default =
  createRequire(import.meta.url)('rollup-plugin-license')

// https://vite.dev/config/
// Vite empties outDir on every build, which would also delete the
// .gitkeep the Go embed (`//go:embed dist/*`) needs so a checkout without
// a UI build still compiles. Recreate it after each build.
function keepGitkeep(outDir: string): Plugin {
  return {
    name: 'keep-gitkeep',
    closeBundle() {
      closeSync(openSync(join(outDir, '.gitkeep'), 'a'))
    },
  }
}

const outDir = '../internal/api/ui/dist'

// Writes dist/licenses.txt: name, version, license, and full license text
// for every third-party package actually bundled into the built console
// (rollup-plugin-license reads this from rollup's own module graph, so
// anything tree-shaken out never appears). The gateway serves this file
// at /licenses.txt (it's a normal file at the dist root -- see
// internal/api/ui/ui.go's spaHandler, which serves any real file under
// dist/ as-is) and it's linked from the console's own sidebar (see
// src/components/layout/Sidebar.tsx). Not committed -- generated by
// `npm run build` like the rest of dist/.
function thirdPartyLicenses(): Plugin {
  // rollup-plugin-license's Plugin type comes from its own `rollup`
  // devDependency, a different (structurally incompatible, though
  // functionally fine) copy of rollup's types than the one Vite's own
  // Plugin type is built from -- a well-known friction between
  // independently-versioned rollup plugins and Vite's re-exported type.
  return license({
    thirdParty: {
      output: {
        file: join(import.meta.dirname, outDir, 'licenses.txt'),
        encoding: 'utf-8',
      },
    },
  }) as unknown as Plugin
}

// @fontsource/* packages (src/main.tsx) are pure CSS + font files, with no
// JS entry point of their own. rollup-plugin-license finds third-party
// packages by walking the *JS* module graph it sees at `renderChunk`
// (chunk.modules), and when more than one such CSS-only package is
// imported from the same file, Vite's CSS-extraction pipeline collapses
// them into a single representative module id there -- verified
// empirically: swapping the import order in main.tsx changes which one of
// @fontsource/inter / @fontsource/jetbrains-mono shows up in
// licenses.txt, never both at once. Patch in whichever got dropped, in
// the exact format rollup-plugin-license's own default template uses, so
// `npm run build`'s licenses.txt is always complete regardless of that
// upstream limitation.
function ensureFontLicenses(outDir: string): Plugin {
  const fontPackages = ['@fontsource/inter', '@fontsource/jetbrains-mono']
  return {
    name: 'ensure-font-licenses',
    closeBundle() {
      const licensesPath = join(import.meta.dirname, outDir, 'licenses.txt')
      let text = readFileSync(licensesPath, 'utf-8')
      for (const name of fontPackages) {
        if (text.includes(`Name: ${name}\n`)) {
          continue
        }
        const pkgDir = join(import.meta.dirname, 'node_modules', name)
        const pkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf-8')) as {
          name: string
          version: string
          license: string
          description?: string
          homepage?: string
          repository?: string | { url?: string }
        }
        const licenseText = readFileSync(join(pkgDir, 'LICENSE'), 'utf-8').trimEnd()
        const repository =
          typeof pkg.repository === 'string' ? pkg.repository : (pkg.repository?.url ?? '')
        const entry =
          `Name: ${pkg.name}\n` +
          `Version: ${pkg.version}\n` +
          `License: ${pkg.license}\n` +
          `Private: false\n` +
          `Description: ${pkg.description ?? ''}\n` +
          `Repository: ${repository}\n` +
          `Homepage: ${pkg.homepage ?? ''}\n` +
          `License Text:\n===\n\n${licenseText}\n`
        text = `${text.trimEnd()}\n\n---\n\n${entry}`
      }
      writeFileSync(licensesPath, text.trimEnd() + '\n')
    },
  }
}

export default defineConfig({
  plugins: [
    keepGitkeep(outDir),
    react(),
    tailwindcss(),
    thirdPartyLicenses(),
    ensureFontLicenses(outDir),
  ],
  resolve: {
    alias: {
      '@': path.resolve(import.meta.dirname, './src'),
    },
  },
  build: {
    // The gateway binary embeds this build via go:embed (see
    // internal/api/ui/ui.go); Vite must write directly into that
    // package's dist/ directory. emptyOutDir clears any stale build
    // (but preserves nothing else -- dist/.gitkeep is regenerated by
    // git, not needed at runtime).
    outDir,
    emptyOutDir: true,
  },
  server: {
    proxy: {
      // The gateway API server runs on :8081 in dev. In production the
      // built app is served by the gateway itself at / on :8081, so all
      // requests are same-origin and this proxy is not needed.
      '/api': {
        target: 'http://localhost:8081',
        changeOrigin: true,
      },
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test/setup.ts'],
    css: true,
    // `npm run test:coverage` (CI) writes coverage/lcov.info for Codecov
    // (flag "web", see ../codecov.yml).
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'lcov'],
      reportsDirectory: 'coverage',
      include: ['src/**/*.{ts,tsx}'],
      exclude: ['src/test/**', 'src/**/*.test.{ts,tsx}', 'src/**/*.d.ts'],
    },
  },
})
